// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceecfypdrmwqzuetgwnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZWNmeXBkcm13cXp1ZXRnd25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTk1MDQsImV4cCI6MjA2MTczNTUwNH0.hbgXimc3lBGqcnYGuirbUAQXi3wP6WPgix-XQqzxf5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);